---
- hosts: web
  gather_facts: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      yum: name=* state=latest

  roles:
    - geerlingguy.nginx
    - geerlingguy.filebeat

  tasks:
    - name: Ensure sie-enabled directories exist.
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/
        state: directory
        mode: 0755

    - name: Set up virtual host for testing.
      copy:
        src: files/example.conf
        dest: /etc/nginx/sites-enabled/example.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: Ensure logs server is in hosts file.
      lineinfile:
        dest: /etc/hosts
        regexp: '.*logs\.test$'
        line: "192.168.56.90 logs.test"
        state: present
